trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Install Dependencies'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x' # Specify Node.js version
    - script: |
        npm install
      displayName: 'Install Dependencies'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    steps:
    - script: |
        echo "No tests available"
      displayName: 'Placeholder for Unit Tests'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Function'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'Azure for Students'
        appName: 'azure-function-app'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
