trigger:
- main  # Adjust to the branch you want to trigger the pipeline on

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Azure for Students'  # Replace with your Azure Service Connection name
  appName: 'azure-function-app'                  # Replace with your Azure Function App name
  resourceGroupName: 'databaseautomation'      # Replace with your Azure Resource Group name
  packagePath: '$(System.DefaultWorkingDirectory)/**/*.zip'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the Azure Function App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'  # Ensure the Node.js version matches your app's requirements
    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build the app'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Tests'
    steps:
    - script: |
        npm test
      displayName: 'Run unit tests'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy Function App to Azure'
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'  # Package the built app
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        replaceExistingArchive: true
    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(azureSubscription)'
        appType: 'functionApp'                                # Specifies deployment to an Azure Function
        appName: '$(appName)'
        resourceGroupName: '$(resourceGroupName)'             # Ensure the resource group matches the app
        package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
