trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
stages:
# Build Stage
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Install Dependencies'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'  # Specify Node.js version
    - script: |
        cd MyApp
        npm install
      displayName: 'Install NPM Packages'
 
# Test Stage
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
    - script: |
        cd MyApp
        npm test
      displayName: 'Run Mocha Unit Tests'
 
# Deploy Stage
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'YourAzureServiceConnection' # Replace with your Azure Service Connection name
        appType: functionApp
        appName: 'app1'                 # Replace with your Azure Function App name
        package: '$(System.DefaultWorkingDirectory)/MyFunctionApp'